platform :ios, '15.0'

target 'App' do
  project 'App.xcodeproj'

  # Capacitor как framework
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios', :modular_headers => true
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios', :modular_headers => true

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['DEFINES_MODULE'] = 'YES'
      end
    end
    # Принудительно собираем Capacitor как framework
    installer.pods_project.targets.each do |target|
      if target.name == 'Capacitor' || target.name == 'CapacitorCordova'
        target.build_configurations.each do |config|
          config.build_settings['MACH_O_TYPE'] = 'mh_dylib'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
  end
end
